version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: escalada
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd!
      MYSQL_DATABASE: bbdd_visa
      MYSQL_USER: visa
      MYSQL_PASSWORD: P@ssw0rd
    volumes:
      - ./Docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  # Agregar tu aplicación Java (esto es un ejemplo)
  app_escalada_visa:
    build: .
    container_name: app_escalada_visa
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    depends_on:
      - mysql
